// Generated by CoffeeScript 1.6.3
(function() {
  var parse, stringify;

  parse = require('css-parse');

  stringify = require('css-stringify');

  module.exports = function(css) {
    var media, mediaRules, medias, parsed, rootRules, rule, rules, _i, _len, _ref;
    parsed = parse(css);
    medias = {};
    rootRules = [];
    _ref = parsed.stylesheet.rules;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      rule = _ref[_i];
      if (rule.type === 'media') {
        if (!medias[rule.media]) {
          medias[rule.media] = [];
        }
        medias[rule.media] = medias[rule.media].concat(rule.rules);
      } else {
        rootRules.push(rule);
      }
    }
    mediaRules = [];
    for (media in medias) {
      rules = medias[media];
      mediaRules.push({
        type: "media",
        media: media,
        rules: rules
      });
    }
    parsed.stylesheet.rules = rootRules.concat(mediaRules);
    return stringify(parsed);
  };

}).call(this);
